version: "3"
services:
 backup:
#  image: nold360/docker-borgbackup
  build: .
  labels:
   one.gnu.docker.backup: "False"
 #  one.gnu.docker.backup.only: "/data,/more/data"
 #  one.gnu.docker.backup.skip: "/more/tmp"
 #  one.gnu.docker.backup.options: "-v --stats"
  environment:
   BORG_REPO: "/backup"
 #  BORG_INIT_OPTIONS: "--encryption=none"
 #  BORG_CREATE_OPTIONS: "-s --progress"
 #  BORG_SKIP_VOLUME_SOURCES: "/proc,/sys,/var/run,/var/cache,/var/tmp"
 #  BORG_BACKUP_ALL: "True"
 #  BORG_BREAK_LOCK: "True"
  volumes:
   - "./borg:/borg"
   - "./backup:/backup"
   - "/var/run/docker.sock:/var/run/docker.sock"
  # - "/srv/:/srv/:ro"
  # - "/var/lib/docker/:/var/lib/docker:ro"
